# Name: Muhammad Musa 
# Email: muhammadmusaimran18.10e@gmail.com
______________________________________________________________________________________________________________________________________________

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.int32)
print(a.ndim, a.shape, a.dtype)
print(a)

2 (2, 3) int32
[[1 2 3]
 [4 5 6]]


1. Create a 5X2 integer array from a range between 100 to 200 such that the
difference between each element is 10 (Hint arange function)

In [3]:

b=np.arange(100,200,10)
print(b)
b=b.reshape(5,2)
print(b)

[100 110 120 130 140 150 160 170 180 190]
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


2. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [4]:
arr1=np.zeros(10,dtype=int)
arr2=np.ones(10,dtype=int)
arr3=np.array([5]*10,dtype=int)
print(arr1,arr2,arr3)
arr4=np.concatenate((arr1,arr2,arr3))
print(arr4)

[0 0 0 0 0 0 0 0 0 0] [1 1 1 1 1 1 1 1 1 1] [5 5 5 5 5 5 5 5 5 5]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


3. Write a NumPy program to generate an 4x7 array of random numbers between
0 and 1

In [5]:
arr2=np.random.randint(0,1+1,size=(4,7))
print(arr2)
arr3=np.random.rand(4,7)
print(arr3)

[[0 1 0 0 1 1 1]
 [1 0 0 1 0 0 1]
 [1 0 1 1 1 1 0]
 [0 0 1 0 1 0 1]]
[[0.05934033 0.90463513 0.30462428 0.58840409 0.80174655 0.80081998
  0.93380008]
 [0.91375091 0.65290655 0.4801557  0.66859838 0.74773694 0.51582411
  0.99475216]
 [0.49414781 0.01283047 0.17904376 0.32507847 0.16379049 0.43341443
  0.46003154]
 [0.42540175 0.09702643 0.69141341 0.37073831 0.81915344 0.0090838
  0.81716963]]


4. Declare the following provided numPy array and print array items the third
column from all rows [[11 ,22, 33], [44, 55, 66], [77, 88, 99]]

In [6]:
arr=np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(arr[:,2])

[33 66 99]


5. Return array of odd rows and even columns from below numpy array
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36],
[39 ,42, 45, 48], [51 ,54, 57, 60]])

In [7]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36],
[39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)
s=sampleArray[1::2,::2] # if we consider row 1 as 0th index and column 1 as 0th index
print(s)

s=sampleArray[::2,1::2] # if we consider row 0 as 1 and column 0 as 1 
print(s)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[15 21]
 [39 45]]
[[ 6 12]
 [30 36]
 [54 60]]


6. Create a result array by adding the following two NumPy arrays. Next, modify
the result array by calculating the square of each element
a. arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
b. arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

In [16]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7,1]])
result=arrayOne+arrayTwo
print(result)
result=result**2
print(result)

[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]


7. Print max from axis 0 and min from axis 1 from the following 2-D array
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

In [9]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
max=np.max(sampleArray,axis=0)
min=np.min(sampleArray,axis=1)
max_index=np.argmax(sampleArray,axis=0)
min_index=np.argmin(sampleArray,axis=1)
print("max = ",max,"  min = ",min)
print(sampleArray)
print("max index: ",max_index,"  max index: ",min_index)

max =  [82 94 73]   min =  [34 12 53]
[[34 43 73]
 [82 22 12]
 [53 94 66]]
max index:  [1 2 0]   max index:  [0 2 0]


8. Delete the second column from a given array and insert the following new
column in its place.
a. sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
b. newColumn = numpy.array([[10,10,10]])

In [10]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray=np.delete(sampleArray,1,axis=1)
sampleArray= np.insert(sampleArray, 1, newColumn, axis=1)
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


9. Print the transpose of the array ([[1,2,3], [4,5,6], [7,8,9]])

In [11]:
arr=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
print(arr.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


10. Convert the following 1D array to a 2D array with 2 rows
a. array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr=arr.reshape(2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
arr=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
num_rows = 2
num_col=arr.size//num_rows
arr=arr.reshape(num_rows,num_col)
print(arr)


[[0 1 2 3 4]
 [5 6 7 8 9]]


11. Create a NumPy array of shape (4, 4) and calculate the sum of all elements,
the sum along each row, and the sum along each column.

In [14]:
arr=np.random.randint(1,10,size=(4,4))
print(arr)
sum=arr.sum()
print("Total sum=",sum)
sum_rows=arr.sum(axis=1)
print("sum of rows",sum_rows)
sum_col=arr.sum(axis=0)
print("sum of columns",sum_col)

[[6 7 2 6]
 [5 4 6 2]
 [5 1 1 9]
 [5 3 4 6]]
Total sum= 72
sum of rows [21 17 16 18]
sum of columns [21 15 13 23]
